accepted = [
    "Apache-2.0",
    "MIT",
    "Apache-2.0",
    "MIT",
    "Unlicense",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MPL-2.0",
    "Zlib",
    "CC0-1.0",
    "ISC",
    "Unicode-3.0"
]
